//
// EventPartialResponseSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EventPartialResponseSchema: Codable {

    public var id: Int?
    /** Connected Venue ID */
    public var venueId: Int?
    /** Name of the event */
    public var name: String?
    public var startTime: Date?
    public var endTime: Date?
    public var tickets: [KeyflowCoreModelSerializerEventSchemaTicketSchema]?
    public var atmosphereIdArray: [Int]?
    public var musicIdArray: [Int]?
    /** List of image strings */
    public var images: [String]?
    public var minimumAge: Int?
    /** Event disclaimer. */
    public var eventLegalDisclaimerReceipt: String?
    /** A description of the event. */
    public var description: String?

    public init(id: Int? = nil, venueId: Int? = nil, name: String? = nil, startTime: Date? = nil, endTime: Date? = nil, tickets: [KeyflowCoreModelSerializerEventSchemaTicketSchema]? = nil, atmosphereIdArray: [Int]? = nil, musicIdArray: [Int]? = nil, images: [String]? = nil, minimumAge: Int? = nil, eventLegalDisclaimerReceipt: String? = nil, description: String? = nil) {
        self.id = id
        self.venueId = venueId
        self.name = name
        self.startTime = startTime
        self.endTime = endTime
        self.tickets = tickets
        self.atmosphereIdArray = atmosphereIdArray
        self.musicIdArray = musicIdArray
        self.images = images
        self.minimumAge = minimumAge
        self.eventLegalDisclaimerReceipt = eventLegalDisclaimerReceipt
        self.description = description
    }

}
