//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse200: Codable {

    public var status: Int
    public var data: InlineResponse200Data

    public init(status: Int, data: InlineResponse200Data) {
        self.status = status
        self.data = data
    }

}
