//
// InlineResponse200Data.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse200Data: Codable {

    public var recommendedEventIds: [Int]?
    public var hotEventIds: [Int]?
    public var discoverEventIds: [Int]?
    /** NOTE: Only the following event fields are returned here: - id */
    public var events: [EventPartialResponseSchema]?
    /** NOTE: Only the following venue schema fields will be returned in this endpoint: */
    public var venues: [VenuePartialResponseSchema]?

    public init(recommendedEventIds: [Int]? = nil, hotEventIds: [Int]? = nil, discoverEventIds: [Int]? = nil, events: [EventPartialResponseSchema]? = nil, venues: [VenuePartialResponseSchema]? = nil) {
        self.recommendedEventIds = recommendedEventIds
        self.hotEventIds = hotEventIds
        self.discoverEventIds = discoverEventIds
        self.events = events
        self.venues = venues
    }

}
