//
// KeyflowCoreModelSerializerDrinktableSchemaDrinkTableExtraParametersSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct KeyflowCoreModelSerializerDrinktableSchemaDrinkTableExtraParametersSchema: Codable {

    public var additionalGuests: Int?
    public var tableRestrictions: String?

    public init(additionalGuests: Int? = nil, tableRestrictions: String? = nil) {
        self.additionalGuests = additionalGuests
        self.tableRestrictions = tableRestrictions
    }

}
