//
// KeyflowCoreModelSerializerV3EventSchemaV3VipCardStatusSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct KeyflowCoreModelSerializerV3EventSchemaV3VipCardStatusSchema: Codable {

    public var cardHolderPaysTicket: Bool?
    public var freeRemaining: Int?
    public var payRemaining: Int?
    public var ticketId: Int?
    public var vipCardId: Int?

    public init(cardHolderPaysTicket: Bool? = nil, freeRemaining: Int? = nil, payRemaining: Int? = nil, ticketId: Int? = nil, vipCardId: Int? = nil) {
        self.cardHolderPaysTicket = cardHolderPaysTicket
        self.freeRemaining = freeRemaining
        self.payRemaining = payRemaining
        self.ticketId = ticketId
        self.vipCardId = vipCardId
    }

}
