//
// KeyflowCoreModelSerializerVenueSchemaVenueLocationSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct KeyflowCoreModelSerializerVenueSchemaVenueLocationSchema: Codable {

    public var locationAddress: String?
    public var locationCity: String?
    public var locationCoordinates: [String]?
    public var locationCountry: String?
    public var locationCountryCode: String?
    public var locationPlaceID: String?
    public var locationReference: String?
    public var locationZoom: Int?

    public init(locationAddress: String? = nil, locationCity: String? = nil, locationCoordinates: [String]? = nil, locationCountry: String? = nil, locationCountryCode: String? = nil, locationPlaceID: String? = nil, locationReference: String? = nil, locationZoom: Int? = nil) {
        self.locationAddress = locationAddress
        self.locationCity = locationCity
        self.locationCoordinates = locationCoordinates
        self.locationCountry = locationCountry
        self.locationCountryCode = locationCountryCode
        self.locationPlaceID = locationPlaceID
        self.locationReference = locationReference
        self.locationZoom = locationZoom
    }

}
