//
// VenuePartialResponseSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VenuePartialResponseSchema: Codable {

    public var venueDescription: String?
    public var venueName: String
    public var venueEmail: String?
    public var venueWebsite: String?
    public var venueLocation: KeyflowCoreModelSerializerVenueSchemaVenueLocationSchema?
    public var venueImages: [String]?
    public var venueLogo: String?
    public var venuePhone: String?
    public var venueAtmosphere: [String]?
    public var venueMusic: [String]?
    public var venueTZ: String?
    public var keyflowCityId: Int?
    public var venueDoorPolicy: String?
    public var venueId: Int?
    public var venueSortRank: Int?
    public var venueUrl: String?
    public var venueLegalDisclaimerReceipt: String?
    public var accountCurrency: String?
    public var venueRglInfoMessage: String?
    public var venueRglInfoColor: String?
    public var venueBidRateMessage: String?
    public var venueBidTimeMessage: String?

    public init(venueDescription: String? = nil, venueName: String, venueEmail: String? = nil, venueWebsite: String? = nil, venueLocation: KeyflowCoreModelSerializerVenueSchemaVenueLocationSchema? = nil, venueImages: [String]? = nil, venueLogo: String? = nil, venuePhone: String? = nil, venueAtmosphere: [String]? = nil, venueMusic: [String]? = nil, venueTZ: String? = nil, keyflowCityId: Int? = nil, venueDoorPolicy: String? = nil, venueId: Int? = nil, venueSortRank: Int? = nil, venueUrl: String? = nil, venueLegalDisclaimerReceipt: String? = nil, accountCurrency: String? = nil, venueRglInfoMessage: String? = nil, venueRglInfoColor: String? = nil, venueBidRateMessage: String? = nil, venueBidTimeMessage: String? = nil) {
        self.venueDescription = venueDescription
        self.venueName = venueName
        self.venueEmail = venueEmail
        self.venueWebsite = venueWebsite
        self.venueLocation = venueLocation
        self.venueImages = venueImages
        self.venueLogo = venueLogo
        self.venuePhone = venuePhone
        self.venueAtmosphere = venueAtmosphere
        self.venueMusic = venueMusic
        self.venueTZ = venueTZ
        self.keyflowCityId = keyflowCityId
        self.venueDoorPolicy = venueDoorPolicy
        self.venueId = venueId
        self.venueSortRank = venueSortRank
        self.venueUrl = venueUrl
        self.venueLegalDisclaimerReceipt = venueLegalDisclaimerReceipt
        self.accountCurrency = accountCurrency
        self.venueRglInfoMessage = venueRglInfoMessage
        self.venueRglInfoColor = venueRglInfoColor
        self.venueBidRateMessage = venueBidRateMessage
        self.venueBidTimeMessage = venueBidTimeMessage
    }

}
